@startuml

title __FILTER's Class Diagram__\n

  namespace cerberus {
    namespace party {
      namespace filter {
        enum PaidPercent {
          All
          p0
          p15
        }
      }
    }
  }
  

  namespace cerberus {
    namespace party {
      namespace filter {
        enum PartyType {
          All
          Birthday
          Celebration
          Farewell
          Wedding
        }
      }
    }
  }
  





@enduml
